In [233]:
import pandas as pd

df = pd.read_csv("../data/full_sales_data.csv")

# Step 1: keep needed columns
df = df[["Date", "Voucher", "Party", "Product", "Qty", "Rate"]]

# Step 2: remove missing rows
df = df.dropna()

# Step 3: remove spaces
for col in df.columns:
    df[col] = df[col].astype(str).str.strip()

# Step 4: remove empty rows
df = df[(df != "").all(axis=1)]

# Step 5: clean Voucher
df["Voucher"] = df["Voucher"].str.extract("(\d+)")

# Step 6: clean numeric columns
df["Qty"] = pd.to_numeric(df["Qty"].str.replace(",", ""), errors="coerce")
df["Rate"] = pd.to_numeric(df["Rate"].str.replace(",", ""), errors="coerce")

# Step 7: remove invalid rows
df = df.dropna()

# Step 8: save cleaned file
# df.to_csv("cleaned_sales.csv", index=False)

In [234]:
import pandas as pd

In [235]:
data = pd.read_csv("../data/full_sales_data.csv")

In [236]:
data

,Unnamed: 0,Date,Voucher,Party,Product,Qty,Rate,Gross,Disc,Voucher Amount
0,0,1/4/2017,Sal:1,SOLANKI PLASTICS,DONA-VAI-9100,2,"1,690.00","3,380.00",NaN,"13,100.00"
1,1,1/4/2017,Sal:1,SOLANKI PLASTICS,LITE FOAM(1200),6,"1,620.00","9,720.00",NaN,NaN
2,2,1/4/2017,Sal:2,SARNESWARA TRADERS,VISHNU CHOTA WINE,500,23,"11,500.00",NaN,"30,990.00"
3,3,1/4/2017,Sal:2,SARNESWARA TRADERS,LITE FOAM(1200),6,"1,620.00","9,720.00",NaN,NaN
4,4,1/4/2017,Sal:2,SARNESWARA TRADERS,DONA-VAI-9100,5,"1,690.00","8,450.00",NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
111201,19171,10/10/2019,Sal:4935,K.SRIHARI,13*16 WHITE RK,400,16,"6,400.00",NaN,NaN
111202,19172,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
111203,19173,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
111204,19174,NaN,Total,NaN,NaN,"99,284.90","175,381.65","2,203,649.50","20,680.00","2,189,014.50"
111205,19175,NaN,Total,NaN,NaN,"2,710,193.00","5,519,888.40","53,360,791.40","672,984.00","52,830,224.40"

In [237]:
data = data[["Date", "Voucher", "Party", "Product", "Qty", "Rate"]]

In [238]:
data.isna().sum()

Date       12591
Voucher    12557
Party         40
Product    12591
Qty        12557
Rate       12558
dtype: int64

In [239]:
data.shape

(111206, 6)

In [240]:
data = data.dropna()

In [241]:
data.isnull().sum()

Date       0
Voucher    0
Party      0
Product    0
Qty        0
Rate       0
dtype: int64

In [242]:
data.shape

(98614, 6)

In [243]:
data.info()

<class 'pandas.DataFrame'>
Index: 98614 entries, 0 to 111201
Data columns (total 6 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Date     98614 non-null  str
 1   Voucher  98614 non-null  str
 2   Party    98614 non-null  str
 3   Product  98614 non-null  str
 4   Qty      98614 non-null  str
 5   Rate     98614 non-null  str
dtypes: str(6)
memory usage: 5.3 MB

In [244]:
party_before_cleaning = data["Party"].unique()

In [245]:
party_before_cleaning

<StringArray>
[   'SOLANKI PLASTICS',  'SARNESWARA TRADERS',                'Lock',
 'khader vali late en',                 'try', 'VAMSI KRISHNA FANCY',
         'DUMMY ENTRY',         'dummy entry',                 'Vkp',
                 'KPR',
 ...
      'shaik sifullaa', 'cethar foods limite',                   'd',
   'suresh adurupalli',             'V.S.BAR',          'LAALU MALL',
 'BALAJI CHEMICALS SU', 'markfed -adurupalli',     '8/10 late entry',
              '10-Jul']
Length: 1835, dtype: str

In [246]:
for col in data.select_dtypes(include="object").columns:
    data[col] = data[col].str.strip()

C:\Users\giris\AppData\Local\Temp\ipykernel_9680\3560895772.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  for col in data.select_dtypes(include="object").columns:

In [247]:
data = data[(data != "").all(axis=1)]

In [248]:
party_after_cleaning = data.Party.unique()

In [249]:
data.info()

<class 'pandas.DataFrame'>
Index: 95561 entries, 0 to 111201
Data columns (total 6 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Date     95561 non-null  str
 1   Voucher  95561 non-null  str
 2   Party    95561 non-null  str
 3   Product  95561 non-null  str
 4   Qty      95561 non-null  str
 5   Rate     95561 non-null  str
dtypes: str(6)
memory usage: 5.1 MB

In [250]:
data["Voucher"] = data["Voucher"].str.extract("(\d+)")

In [251]:
data["Qty"] = pd.to_numeric(
    data["Qty"].astype(str).str.replace(",", ""), errors="coerce"
)

In [252]:
data.Rate = pd.to_numeric(arg=data.Rate.str.replace(",", ""), errors="coerce")

In [253]:
data.Voucher = pd.to_numeric(arg=data.Voucher.astype("Int64"), errors="coerce")

In [254]:
data = data.dropna()

In [255]:
# data.Date = pd.to_datetime(arg=data.Date, errors="coerce")

In [256]:
removed_values = set(party_before_cleaning) - set(party_after_cleaning)

print(removed_values)

{'sss', 'svr wines marripadu', ',msr catering', 'll', 'msr', 'a.srinivasulu baglo', 'KMS,KHADERVALI dobl', 'sriramsrinivasulu c', 'arla', 'satyam-vgiri', 'skt', 'gajendra', 'SHANMUGA PROVSION', 'SSR', 'P.SUNDARAMA,JAMALA,', 'nta', 'BABU REDDY,M.PENCHA', 'YVT PMR', 'KHADERVALI,P.SUNDAR', 'b', 'ion', 'svs water plant -vg', 'v.venkateswaralu', '@110', 'prabhakar', 'surya provsion', 'INV 19', 'SVT KOTA', 'ENTERED IN 30/5', 'msr caterin', 'slv', 'aram', 'gunta', 'l.mohanrao', 'radhakrishna', 'KSR -ISKAPALL', 'suresh /srikalahast', 'm.suresh skht', 'g', 'mallaya,kks', 'direc auto', 'raya', 'FOODS', 'a', 'LATE ENTRY', 'saraswathi hotel', 'CREDIT AUTOLO', 'svr brandhi shop', 'VASUNDARA MAHILA MA', '750 lids pending 6 ', 'karumulla', 'jarla', 'dhvara', 'g.madhu -kaluvai', ' llids complete', 'tkr-bitragunta', 'aruna hotel', 'kms,sss', 'suraypalem', 'lakshmifancy', 'niranjan', 'pvs nagaletuur', 'BABAMESS', 'dkr', 'KARIMULL', 'A.VENKATESWARLU-VB ', 'GIRI ATMAKUR', 'prakash,msr', 'ATESWARLU', 'tirumala from a.sri', 'cvs-railway kodur', 'shaik sifullaa', 'madhu provisiion', 'neelakanta reddy', 'kalyani fruit juic', 'ms spt', 'BSM', 'b.satyam', 'credit bill suresh ', 'svt-kota', '15/6 date bill', 'ngam', 'sk. babu ,ramu', 'boxes', 'SION-SANGAM', 'l', 'g.mahdu.madhuprovis', 'epalem', 'svr brandishop', 'k.kannaya', 'kammapali road', 'ending, old pending', 'ganesh water plant', 'gajendraa', 'BARGAV PROVISION', 'T', 'malyadri autolo', 'LATE ENTRY 3/2', 'KSR - GUDUR', '42/3', 'hampi stores', 'GMR', 'v.giri', 'dali', '65/2', 'krishna cool drinks', 'HAZARATH REDDY-CHEJ', ',PABBISETYY', 'AUTOLO HUSSAIN', 'crediit bill', 'p.sundarm', 'subharao', 'jbr,k.sandep', 'KMS,KV', 'LATE ENTRT', ' changed', 'GV,SHODA BANDI VENK', 'raja fancy-kaluvai', 'shaik sifull', 'muralikvl', 'on', 'credt bill', 'satyam credit bill', 'credi biill', 'TSR', '4/7 vehicl', 'BROWN TAPRROLL', 'kvs', 'mr', 'P.SUNDARAM NPT', 'sk sifulla', 'BABU FANCY', 'purnasai 30/8', 'entered on 27/9', 'gvs', 'GRK', 'nn pdkr', 'rajesh', 'ear', 'ssr', 'giri', 'direct from kavali', 'silver pouchi 7-*9', 'khadervali9', 'p.prabhakar -iskapa', 'credit bill autlo', 'a.venkatreddy dcc b', 'credit bill by hand', 'jamal ,khadervali', 'p.prabhakar', 'vasundara mahilaman', 'arripadu', 'khader vali late en', '18count 17/4', 'madhu provisions-ma', 'kondareedddy', 'st-npt', 'karimulla,sri rama ', 'K.SRIHARI,MR', 'pet', 'md rafi', 'k.neelakantareddy', '18/5', 'VS', 'HAMMA', 'radhakrishn', 'price difference', 'sriram srinivasul', 'preethi super marke', 't.venugopal', 'ramu', '20/9 ENTERED', '31/07 ENTRY CHESAM', 'CDREDIT BILL', '1-Jul', 'r and r ,gopi', 'credit bill autolo', 'RAJESH DAKKILI', 'brhamiah,rajafancy,', 'sss-spt', 'velindi', 'ark', 'v.venkateswarlu', 'MSR CATERING ,JAMAL', 'M.S-SPT', 'shaar return items', 'MADHUSUDHAN-NPT', 'swarlu-duttalur', 'k.kumar', 'neral stores', 'bvr', 'svs waterplant', 'G.MADHU,MADHU PROVI', 'st', 'GAJENDRA,J.RATHAYYA', 'padmavathi', 'P.M SWAMI', 'p.lalith', 'KHADARVALLI,khadera', 'SVR WINES', 's-kotha gunta', 'TED', 'SARAVANA TENKAYALA ', 'direct', 'svr wine', 'sandeep -vgiri', '23/3', 'msr catering npt', '51/3', 'govardhan npt', 'd.surendra-chilakal', 'VASUNDARA MAHILAMAN', 't.mohan', 'mt', 'gam', 'd.veerabadram,vijay', 'm.suresh/skht', 'khader vali', 'S KOTHA GUNTA', 'tirupathi redy', '3-Feb', 'u', 'GCC KALUVAI', 'harihara steels', 'ta', 'pending lids all cl', 'ak.gopi', 'kothagunta meera ge', 'SSS SPT', 'chitweli', 'WINE BAHUBALI DEDUC', 'SBH', 'G.MADU', 'geethika provisions', '3/9 WBB', 'autolo', 'M.SURESH T.K.PADU', 'ss duttaluru', 'ak.gopi,d.venkayya', 'grk,kvr', 'PVS', '91/2', 'khadervali,jamal', 'hampistores', 'balaji brandi shop', 'kms kvkc nundi', 'venkateswarlu amoun', 'entered on 09/10', 'brown tape rolls', 'kavali vehicle', 'date 30/9 ani vundh', 'my swami devastanam', 'RPS -UGIRI', '75/2', 'KHADERVAIL', 'h', 'venugopal', 'krb', 'MSR CATERING NPT', 'siva tiifin centre ', 'D.VEERABADHRAYA', 'SVT -KOTA', 'pp balance', 'v.siva', 'ch.redd', 'M.RAMARAO-CHINAMACH', 'p.raja spt', 'K.SUDHAKAR', 'credit bills', 'p.sundaram late ent', 'late entrt', '.SURESH', 'svr brandi shop mar', 'g.madhu-kaluvai', 'lids pending', 'ripadu', 'dummy entry', 'vinayaka sweets kot', 'kondaredyy', 'ORDER', 'KARIMULLA', 'msr catreing', 'entered on 04/10', '2ND DAY', 'kmn', 'SANDEEP VGIRI', 'purna fancy stores', 'surendra', 'sk .babu', 'psm', 'RAJA FANCY', 'credi bill', 'AK.GOPI,P.PRABHAKAR', 'rajafancy,l.mohanra', 'RK', 'SRI RAM SRINIVASULU', 'zameer autolo', 'sandeep', 'INV 12', 'vali', 'KARIMULLA,BRR', 'madhuprovisions', 'SHAJAHAN NPT', 'pmr madhuprovision', '10-Jul', 'AK.GOPI', '27/9 entered', 'grk-vgiri', 'e palme', 'madhu provision -sa', 'veerabadrayya kalah', 'credit ill', ' in april', 'ch.tirupathi', 'sivakumar', 'csn spt', '18 count', 'ds', 'PH ATMAKUR', 'OPPOSIT MARKET', 'dkr,sandeep', 'parcel on wednesday', 'gg', 'gmr', 'tirupal reddy-kalig', 'bala autolo', 'vijaylakshmi provis', 'brown taperoll', 'VEERABADRAY', 'sola suresh', 'CREDIT BLL', 'gsr', 'ores', 'sifulla', 'vijayalakshmi', 'customer', '28/3', 'murali-kothagunta', 'guntur venkateswarl', 'CH.ANKAYYA', 'gmr-npt', 'CH.TIRUPATHI -NELLO', 'DALI', 'p.sundaram', 'pvs', 'INTREST', 'geethika', 'veerabadhrayya skht', 'amal', 'INV 17', 'p.vraja', 'astanamma', '1', 'lalithamma', 'MT,KHADERVALI', 'SUBHIAH', 'k.chandra', 'janatha traders', 'g.subharao', 'CM FANCY', 'shajahan npt', 'obulreddy', 't', 'venkateswarlu', 'KHADERVALI,', 'gopinath', 'direcht vehicle', 'allaya', 'direct vehicle', 'entered on 27/12', 'pv raghavareddy ---', 'khadervalli-spt', 'sri raam subharao', 'GAJENDRA', 'balaji brandi shop-', 'igiri', 'msr caterng', 'N.RAMANAREDDY -GDR', 'parvathi parameswar', 'amarri', '30/08,05/09,09/09', 'j.basker', 'p.sundaram,prakash', 'jyothi fancu', 'venakatesh', ' 6-120 ki amount 42', 'CREDDIT BILL', 'entered on 15/9', 'v.venk', 'svr brandhi', 'AADHAR NO 842144570', 'abc', 'vasundaramahilamand', 'BRR-VGIRI', 'cycle bk old pendin', 'shoda bandi venkate', 'khadervali', 'shajahan-npt', 'by byke', 'RAJAFANCY', 'k.subhramanyam', 'GSR', 'late entruy', 'ssr-npt', 'hazarath reddy-chej', 'extraga vesam', 'ndram', 'durga bhavani', 'PSM SPT', 'bnr -chintalathmaku', 'SURESH', '30/11', 'shajahan,prakash', '27/4', 'mgn', 'damaramadugu', 'subhareddy autolo', 'MRR', 'hagunta', 'gajendra skht', 'sairam provisions', 'ps', '57/3', '13*16 RK W RETUN IC', 'RAVI', 'spr kota', 'KRISHNA COOLDRINGK', 'surya prakash rao -', 'ENTERED on 15/9', '2nd time', 'babamess-vgiri', '8/10 late entry', 'PRATHAP', 'SLS', 'ak gopi,g.madhu', 'p.sundaram,kms/spt', 'PABBISETY', 'sh sifulla', 'AK GOPI', 'astores', 'svt kota', 'INV 16', 'ksr', 'V.S.BAR', 'madhu provision-san', 'P.SUNDARAM,SK.BABU ', 'GKR RAPUR', 'LOCK', '0', 'NOT ENTERED', 'JBR', 'T.RAVI', 'hazarath reddy', 'G.MADHU', 'MAHESWARA GENERALS', 'r', 'VSR BTTR', 'p.v.raja vgiri', 'vishnu', 'despathed on 8/8', 'khaja menon', 'P', 'suresh skht', 'sai electrricals', 'M.SURESH', 'shaik sifulla', 'VLN VAKADU', 'raja fancy', 'SVR BRANDHI', '23*30', 'CREDIT ILL', 'BABUFANCY', '20/7 late entry', 's', 'svt', 'e', 'u-pamur', 'd.veerabaram', 'direct vechil', 'VGIRI ROAD', 'DURGA BHAVANI', 'direct vehicl', 'krishna cooldrinks', 'april 3rd', 'nilakantareddy', 't.ravi beeranguta', 'srinivasa gdr', 'credi bil', 'khadervali-spt', 'pvs nagaleturu', 'klr', 'karimulla -vigir', 'asthi', 'ssb-1,svr wines-1', 'LNFS-VGIRI', 'ank chitweli', '3/4 sifulla', '85/2', 'sk.babu,kms', 'NAGIREDDY', 'msr catering late e', 'lalithamm', 'l.mohanrao,j,bhaske', '29/5', 'G.SUDHAKAR', 'khader valli', 'DURGA PLASTICS', 'khaderval', 'rajafancy,g.madhu', '13/3 late entry', 'o,madhu provisions', 'kks', 'SK SIFULL', 'cvr', 'late entrhy', 'amma daggar', '5-Jul', 'ravi wines -bangaru', 'chool', 'ASH,SK.BABU,SUNDARA', 'sion', 'direct vechicle', 'k.madhu,gmr', 'lt', 'CREDIIT BILL', 'p.s,msr catering', 'LIDS PENDING CLEAR', 'credit', 'rajafancy,pvs,grk', 'shajahana', '16/04', 'cethar foods limite', 'SUDHAKAR', 'SUDHAKAR- BITRAGUNT', 'credit bill meera g', 'SLST', 'AUTLO', 'khadervai', 'R.HAZARATHAIAH -ATK', 'AM', 'balu autolo', 'ali -somasila', 'g.kumar naidupet', 'P.SUNDARA', 'HADU 3200 LESS', 'karimulla', 'vinayaka sweet', 'surya provisions', 'ksm', 'ntry', 'BRR', 'DIRECT VEHICL', 'T.SUDHAKAR', 'sk.babu', 'BABU FANCU', 'SUNDARAM NPT', 'directh autolo', 'marripadu', 'vinayaka sweets-kot', 'sap 25kg amount les', 'p.raja', 'RAJYALAKSHMI PAPER ', 'DHAMARAMADUGU', 'late entyr', 'auto', '17/2', 'M.SURESH,GRK', 'DIRECT VECHICL', '4/3 LATE ENTRY', '250ML LESS', 'RAJASURESH KI', 'PRAKAS', 'extra lastlo', 'direct from hyderab', 'p.sundara', '4/1/2019 late entry', 'sk.babu,prakash', 'hi', 'babu', 'KHADERVALI,KK', 'entered on 15-9', 'bismill traders', '95/3', 'tsr', 'vinayaka sweeets an', 'acr', 'gsr,murali-kothagun', 'creddit bill', 'VIJAYLAKSHMI PROVIS', 'l entry chesam', 'PRAKASH', 'bismilla trader', 'p.v.raja', '18/2', 'bkr-adurupall', 'ramanareddy', 'kbr', 'sk,babu,shajahan', 'A', 'ramesh enterprises', 'NR PDKR', 'gvs-vb palli', 'md isaq', 'credit bll', 'MS', 'saturday boxes', 'G.MADHU,SANDEEP,P.L', '18/7,24/07,04/08,14', 'mahindra fertilizer', 'ath', 'SRIRAM SRINIVASULU', '6/12,19/12', '750 lids -20boxes p', 'vasundara mahil', 'N 0504 2018', 'girija medicals', 'sreeram eswarayya', '20count', 'karimull', 'suresh adurupalli', 'credibill', '920', 'AGAR', 'VLN', 'credit bill', 'lalith skht', '4/2 direct vehicle', 'svr brandis', 'ANUR', ' velindi', 'direct vechcle', 'jamal sulurpet', 'T.VENUGGOPAL', 'srinivasulu,ys', 'PREETHI SUPER MARKE', 'svr brandi shop -ma', 'paid', 'GAM', 'bismilla', 'chandra mouli -vgir', 'vijaya stores', 'rkk', 'LALITHAMMA', 'GSR MALLAM', 'radhama alluru', 'mt,msr,p.sundaram,d', 'T,MADHU PROVISION,M', 'DIRECT VEHICLE', 'not entered', 'SVR BRADISHOP', 'LS', 'entered on 15/8', 'ugiri', 'vowel india school', 'balu autol', 'KMS,KHADERVALI', 'j.bhasker,gajendra', 'ions', 'sk babu,prakash,kms', 'MAHDU PROVISON', 'try', 'vellindi', 'late entr', 'N.RAMANIAH', 'hazarath reddy chej', '1kg weight', 'g.madhu-kaluva', 'vasundara mahila', 'd.veerabadhram', 'BISMILLLA TRADERS', 'direct autolo', 'khadervali.sk babu', 'swarlu', 'SATISH-NPT(PILLARI ', 'SVR BRANDI', 'epale', 'kvkc nundi mallay', 'credit bill autolo ', 'sandhanibash', 'eneral stores-kotha', 'RAMANA REDDY', 'j.rathia', 'nagireddy fancy', 'MSSR CATERING', 'CH.TIRUPATHI', 'R', 'INV NO 15', 'power bill', 'kondareddy 2nd time', '74/2', 't.venkateswarlu', 'KOTHAGUNTA', 'KHADERVALI SPT', 'prathap autolo', 'G.LAKSHMI', 'sriram subharao ---', 'entered on 17', 'yvt pmr', 'vinayaka sweets', 'kondareddy', 'GRK,LALITHA', 'mr,j.rathay', 'acr-pdkr', 'pp 5*6 olddhi', 'sundaram', 'enerals ----kothagu', 'SK.BABU,PRAKASH', 'VSR CHITWELI', 'gsr mall', 'AUTOLO CREDIT BILL', 'CREDIT BIL', 'stores', 'vsm malli karjuna', 'idhi 12-07-2017 bil', 'vali,mallaya', 'old pending', 'grk,kannaya', 'dakkili', '2/2 LATE ENTRY', 'i', 'smart boul quantity', 'vasu water venkatag', 'gg,m.suresh,y.gopin', 'SHAIK SIFULL', 'ak.gopi,g.madhu,kat', 'markfed', 'gsr malla', 'SUDHAKAR SING', 'rripadu', 'crdit bill', 'siva fancy', 'sandeep ,penchalay', 'gurram bhasker', 'vlp', 'pvr madapalli', 'B.SATYAM VGIRI', 'hadervali,mallaya,j', 'shajahna', 'self', '/08', 'LATEENTRY', 'V.VENKATESWARLU', 'shajahan', 'satyam', 'RADHAMMA', 'credit biill', 'ms ramu', 'PAID', 'KKAR', 'SVR BRANDI SHOP', 'SANDEEP', 'KONDAREDDY', 'grk', 'bsr', 's.malakondareddy', 'KANYAKAPARAMESWARI ', 'direct autoo', 'gvi', 'nn', 'MVSR', 'b.subhara', 'ch.tirupathi-nellor', 'SVS WATERPLANT', 'M', 'sairam', 'D.VEERABADRAYYA', 'PBNR', 'balai brandishop', 'sriharinunchi', 'without lids', 'vln', 'tirupal reddy -kali', 'nellakantarddy-vgir', 'jamal', 'cvr railway kodur', 'ravifancy,venugopal', 'gssr', 'P.LALITH', '51.5@110', '7/1/2019', 'HAREDDY', 'GURUNATHAM GENERAL ', 'ramana reddy -gudur', '32/3', 'storess', 'S', 'jbr vgiri', 'm.suresh,d.veerabad', 'msr catering ,khade', 'kkr', 'MADHU PROVISION,SES', 'svr venkateswarlu p', 'y.gopinath,jbr', 'credit autolo', 'veerabadraya', 'G.SUBHARAO', 'MEERA GENERAL STORE', 'd', 'k.chandra -kurugond', 'VASUNDARA', 'brr', 'JAMAL-SPT', 'autollo', 'atmakur', 'j.bhasker', 'gsr,sandeep ,g.madh', 'preethi supermarket', 'BY HAND', 'STORE', 'lli', 'STORES', 'SRI SAIRAM GENERAL ', '4/1 late entry', 'PRIYA MEDICAL', '120+120+135', 'k.leelavathi', 'PRAVEEN', 'AKBAR COOLDRINK', 'hagunt', 'pabbisetty', 'P.SUNDARAM', 'current bill', 'murali kothagunta', 'suresh -adurupalli', 'ch.tirupathi nellor', 'p.seethamma,shaik m', 'sls', 'mgs-npt', 'd bakery', 'vasundara', 'entered', 'raghu -pdkr', 'SURESH ,BUJJAYA,SUB', 'svr brandi shop', 'prakash', 'gvs provisions', 'direct aulto', 'puja traders skht', 'bv subhramanyam,gsr', 'karthik department', '#NAME?', 'CREDIT BILLL', 'kms', 'p.sudaram', 'a.ramesh-atkr', 'april 2nd', 'rajafancy', 'svr brhandhi shop-m', 'seshamma-alr', 'v.srinivasulu', 'kondayya credit bil', 'entered 15/9', 'CREDTI BILL', 'k.neela kantareddy', 'MADHU PROVISION-SAN', 'CREDIT BILL', '73/3', 'kavali direct', 'NUNNA NARAYANA/PDKR', 'kms,sss,khadervali', 'PSM', 'prakash ,khadervali', '26/9', 'ssr npt', 'msr catering,kks', 'WARLU-DUTTALUR', 'surayapalem', 'p.lalitha', 't.raghu', 'lem', 'sai departmental st', 'sriram srinivasulu', 'silver 7 900,tiffin', 'MALLAYA ,JAMAL', 'vln vakadu', '\\', 'veerabadram', 'credt bil', 'gurram dasayy', 'm.chandra', 'latentry', 'SODA BANDI VENKATES', 'credit billl', 'seshamma', '86/2', 'colour glass', 'ravi wines', 'ad', 'bsr pindimillu -kal', '5-Oct', 'by hand', 'prakash npt', 'madhu provisions', 'g.kumara', 'TAPE ROLL N-3 BROUN', 'olddhi', 'sk babu', 'suresh', 'jay', 'beedilaki amount', 'sandeep vgiri', 'cash', '73/2', 'b.sudhakar-singapet', 'svs water plant', 'KARIMULLA,MS RAMU', 'suresh kalahasthi', 'yugandhar-skht', 'mssr catering', 'CREDIT IBLL', 'ION', 'store', '14/4', 'markfed -adurupalli', 'late entru', 'RE PALEM', 'shajahan,p.sundaram', 'svsgs', 'vasundara mahilmand', 'credit ibll', 'srinivasulu', 'chandra', 'ravindra bharathi s', 'M.BABUREDDY', 'brown tape roll', 'kms late entry', 'svr brandi', '25/2', 'SHANMUGA PROVISSIN', 'DUMMY ENTRY', '22/4 27/4', '9290125676', 'foods', 'asulu-madapalli', 'babu fancy', 'hazarath reddy -che', 'prakash,msr caterin', 'nagireddy', 'k.neelakanta reddy', 'DIRECT HYD', 'LALITHAMM', 'repeated items less', 't.ravi', 'madhuprovsions', 'hari hara cements', '-3', 'madhu provision ssa', 'kms,sss,khadervali,', 'madhu provison', 'g.madhu,madhu provi', 'bsm box -4/9 datedh', 'BOR', 'd.veerabadram', 'chatla narayana', 'e entry', '5/2 late entry', 'jbr', 'bhavani juice-rapur', 'mallaya', 'HAMPI STORES', 'teladoddi', 'credir bill', 'KHADERVALI,JAMAL', 'ravi', 'AUTOLO LATEENTRY', 'dona new price', 'shajahan,', ' AND BAKERY', 'meghanabar', 'RK /SITHALUR', 'shajahan,khadervali', 'RATNAM FANCY', 'entered on 25/10', 'r vali late entry', 'late entry', 'RADHAKRISHNA-SPT', 'provision', 'madhu provision', 'VENKATESWARALU', 'AUTOLO', 'L REDDY', 'G.MADHU -KALUVAI', '20/9 entered', 'subhareddy', 'quality', 'muralihotel', 'meera general store', 'credt bll', 'SVT-KOTA TENKAYALA ', 'ndali', 'MSR CATERING,p.sund', 'B', 'jsv less 93', 'MADHU PROVISION', 'p.s', '60/2', 'gsr mallam', '18/5,1/6', 'VS SPT', '25/2,1/3,3/3,5/3', 'g.madhu', 'CHENCHUMAHALAKSHMI ', 'surya provision', 'psm spt', 'direct auto 4/3', 'd.veera badra,sures', 'vasundhara mahilama', 'sri ram srinivasulu', 'Y,GOPINATH', 'raghu', 'tkr bitragunta', 'venugopal,', 'tirupathi nellorepa', 'MS RAMU', 'durg plastics', '1/4, 15/3', 'credit bil;', 'vln -vakadu', '15/9 madras', 'large cups', 'y.gopinath', 'PVS ALR', 'DIRECT AUTLO', 'SK SIFULLA', 'G.KUMARA', 'KMS,KHADERVALI,PRAK', 'AUTULO', 'ch.reddy', 'TIRUPAL REDDY', 'autolo-credit bill', '13/5 LATE ENTRY', 'lavanya autolo', 'SK.BABU', 'P.V.RAJA', 'DIRECT AUTOLO', 'chekkarangaya', 'jagadeesh', 'madhuprovision', 'shanmuga provision', 'KHADERVALI', 'ravi fanc', 'direct auto', 'SRINIVASULU-BTTR', 'niivasulu', 'iri', 'sri kodanda ramaswa', 'msr catering', 'kch', 'prakahs', 'cm npt', 'babamess', 'kaluvai', 'r rao', 'changes with old bi', 'vasundhara', 'ALITHA', 'girija medical', 'mahesh', 'NUNNA NARAYANA', 'S-KOTHAGUNTA', 'm.suresh', 'SRI VINAYAKA SWEETS', 'TIRUPATHI REDDY', 'jamal-spt,shajahana', 'vinayak wine -kotha', '29/07 late entry', 'svr bradi shop', '22/4', 'm.suresh-skht', 'sed,1000 ml less', 'no-7', 'ry', 'ali', '15/4', 'SATYAM', 'autlo', 'from hyd', '17/3', 'KMS', 'msr catering,khader', 'mgs', 'bismilla traders', 'sk. babu prakash', 'K.NARASIMHA NAIDU', 'g.madhu kaluvai', 'SK .BABU,PRAKASH', 'kms spt', 'credit bill auto lo', 'v.giri,ak gopi', 'sbh /chennuru', 'svr wines', 'prathap', 'CHANDU CONSTRUCTION', 'neelakantareddy', 'with lids', 'm.jagadeesh', 'MURALI MESS -VIDYAN', 't.sudhakar', 'khader vali,mallaya', 'ENTERED THIS BILL O', '19/8', 'jamal spt', 'VIJAYA STORES', 'extra vesam', 'g.kumar', 'mahesh bttr', 'RADHAKRISHNA -SPT', 'sk babu,p.s', 'MSR CATERING', 'T.VENUGOPAL', 'radhakrishna-spt', 'GSR-MALLAMA', 'govardhan', 'hakalikonda', 'SRAVANI PROVISION', 'manubolu', 'ARLA', 'PV.RAJA', 'NN', 'vijay stoers', 'ratnam fancy palake', 'SHAJAHAN', 'ms-spt', 'april 2nd bill', 'ch.ramaniah', 'G.GURAVIAH', '267', 'kch kalahasthi', 'credit bil', 'NDALI', 'CREDIT BILL AUTOLO', 'kms,khaderval,sss,m'}

In [257]:
data1 = pd.read_csv("../data/Sales-Transactions-Edited.csv")

In [258]:
data.equals(data1)

False

In [259]:
different_rows = pd.concat([data, data1]).drop_duplicates(keep=False)

different_rows

,Date,Voucher,Party,Product,Qty,Rate
6,1/4/2017,898,Lock,Vishnu 250ml,100.0,30.0
7,1/4/2017,898,Lock,BLACK DOG-350ML,100.0,26.0
10,1/4/2017,2497,VAMSI KRISHNA FANCY,Loose Items,1.0,800.0
13,1/4/2017,9263,VAMSI KRISHNA FANCY,Loose Items,1.0,280.0
16,1/4/2017,9545,Vkp,Loose Items,1.0,695.0
...,...,...,...,...,...,...
95538,12/9/2019,4255,KVKC,HARITHA M.W 13*16,60.0,84.0
95542,12/9/2019,4258,SREERAM ESWARAYA-AT,VISHNU 300ML,100.0,29.0
95545,12/9/2019,4260,KVKC,BLACK DOG-350ML,660.0,22.0
95546,12/9/2019,4260,KVKC,CITIZEN 13*16-M.W,25.0,90.0
95559,12/9/2019,4267,SMS,SMARTBOUL GLA(4000),1.0,1520.0

In [260]:
data.info()

<class 'pandas.DataFrame'>
Index: 95561 entries, 0 to 111201
Data columns (total 6 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Date     95561 non-null  str
 1   Voucher  95561 non-null  Int64
 2   Party    95561 non-null  str
 3   Product  95561 non-null  str
 4   Qty      95561 non-null  float64
 5   Rate     95561 non-null  float64
dtypes: Int64(1), float64(2), str(3)
memory usage: 5.2 MB

In [261]:
data1.info()

<class 'pandas.DataFrame'>
RangeIndex: 95562 entries, 0 to 95561
Data columns (total 6 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Date     95562 non-null  str
 1   Voucher  95562 non-null  int64
 2   Party    95562 non-null  str
 3   Product  95562 non-null  str
 4   Qty      95562 non-null  int64
 5   Rate     95561 non-null  float64
dtypes: float64(1), int64(2), str(3)
memory usage: 4.4 MB

In [263]:
# data.compare(data1)