# Model Optimization Techniques
- Improve the model performance w.r.t accuracy score, precision_recall tradeoff, etc...


1. Standard Scalar - Mean 0 and Standard Deviation 1
2. MinMax Scalar
3. Robust Scalar


- While optimization the model training time will also get decrease

## 1. Import Necessay Libraries

In [928]:
from sklearn import datasets
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split

## 2. Import Dataset

In [929]:
breast_cancer_data = datasets.load_breast_cancer()

In [930]:
print(breast_cancer_data.DESCR)

.. _breast_cancer_dataset:

Breast cancer Wisconsin (diagnostic) dataset
--------------------------------------------

**Data Set Characteristics:**

:Number of Instances: 569

:Number of Attributes: 30 numeric, predictive attributes and the class

:Attribute Information:
    - radius (mean of distances from center to points on the perimeter)
    - texture (standard deviation of gray-scale values)
    - perimeter
    - area
    - smoothness (local variation in radius lengths)
    - compactness (perimeter^2 / area - 1.0)
    - concavity (severity of concave portions of the contour)
    - concave points (number of concave portions of the contour)
    - symmetry
    - fractal dimension ("coastline approximation" - 1)

    The mean, standard error, and "worst" or largest (mean of the three
    worst/largest values) of these features were computed for each image,
    resulting in 30 features.  For instance, field 0 is Mean Radius, field
    10 is Radius SE, field 20 is Worst Radius.

    - class:
            - WDBC-Malignant
            - WDBC-Benign

:Summary Statistics:

===================================== ====== ======
                                        Min    Max
===================================== ====== ======
radius (mean):                        6.981  28.11
texture (mean):                       9.71   39.28
perimeter (mean):                     43.79  188.5
area (mean):                          143.5  2501.0
smoothness (mean):                    0.053  0.163
compactness (mean):                   0.019  0.345
concavity (mean):                     0.0    0.427
concave points (mean):                0.0    0.201
symmetry (mean):                      0.106  0.304
fractal dimension (mean):             0.05   0.097
radius (standard error):              0.112  2.873
texture (standard error):             0.36   4.885
perimeter (standard error):           0.757  21.98
area (standard error):                6.802  542.2
smoothness (standard error):          0.002  0.031
compactness (standard error):         0.002  0.135
concavity (standard error):           0.0    0.396
concave points (standard error):      0.0    0.053
symmetry (standard error):            0.008  0.079
fractal dimension (standard error):   0.001  0.03
radius (worst):                       7.93   36.04
texture (worst):                      12.02  49.54
perimeter (worst):                    50.41  251.2
area (worst):                         185.2  4254.0
smoothness (worst):                   0.071  0.223
compactness (worst):                  0.027  1.058
concavity (worst):                    0.0    1.252
concave points (worst):               0.0    0.291
symmetry (worst):                     0.156  0.664
fractal dimension (worst):            0.055  0.208
===================================== ====== ======

:Missing Attribute Values: None

:Class Distribution: 212 - Malignant, 357 - Benign

:Creator:  Dr. William H. Wolberg, W. Nick Street, Olvi L. Mangasarian

:Donor: Nick Street

:Date: November, 1995

This is a copy of UCI ML Breast Cancer Wisconsin (Diagnostic) datasets.
https://goo.gl/U2Uwz2

Features are computed from a digitized image of a fine needle
aspirate (FNA) of a breast mass.  They describe
characteristics of the cell nuclei present in the image.

Separating plane described above was obtained using
Multisurface Method-Tree (MSM-T) [K. P. Bennett, "Decision Tree
Construction Via Linear Programming." Proceedings of the 4th
Midwest Artificial Intelligence and Cognitive Science Society,
pp. 97-101, 1992], a classification method which uses linear
programming to construct a decision tree.  Relevant features
were selected using an exhaustive search in the space of 1-4
features and 1-3 separating planes.

The actual linear program used to obtain the separating plane
in the 3-dimensional space is that described in:
[K. P. Bennett and O. L. Mangasarian: "Robust Linear
Programming Discrimination of Two Linearly Inseparable Sets",
Optimization Methods and Software 1, 1992, 23-34].

This database is also available through the UW CS ftp server:

ftp ftp.cs.wisc.edu
cd math-prog/cpo-dataset/machine-learn/WDBC/

.. dropdown:: References

  - W.N. Street, W.H. Wolberg and O.L. Mangasarian. Nuclear feature extraction
    for breast tumor diagnosis. IS&T/SPIE 1993 International Symposium on
    Electronic Imaging: Science and Technology, volume 1905, pages 861-870,
    San Jose, CA, 1993.
  - O.L. Mangasarian, W.N. Street and W.H. Wolberg. Breast cancer diagnosis and
    prognosis via linear programming. Operations Research, 43(4), pages 570-577,
    July-August 1995.
  - W.H. Wolberg, W.N. Street, and O.L. Mangasarian. Machine learning techniques
    to diagnose breast cancer from fine-needle aspirates. Cancer Letters 77 (1994)
    163-171.

In [931]:
breast_cancer_data.feature_names

array(['mean radius', 'mean texture', 'mean perimeter', 'mean area',
       'mean smoothness', 'mean compactness', 'mean concavity',
       'mean concave points', 'mean symmetry', 'mean fractal dimension',
       'radius error', 'texture error', 'perimeter error', 'area error',
       'smoothness error', 'compactness error', 'concavity error',
       'concave points error', 'symmetry error',
       'fractal dimension error', 'worst radius', 'worst texture',
       'worst perimeter', 'worst area', 'worst smoothness',
       'worst compactness', 'worst concavity', 'worst concave points',
       'worst symmetry', 'worst fractal dimension'], dtype='<U23')

In [932]:
breast_cancer_data_df = pd.DataFrame(data=breast_cancer_data.data, columns=breast_cancer_data.feature_names)

In [933]:
breast_cancer_data_df["target"] = breast_cancer_data.target

In [934]:
breast_cancer_data_df

,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,mean fractal dimension,...,worst texture,worst perimeter,worst area,worst smoothness,worst compactness,worst concavity,worst concave points,worst symmetry,worst fractal dimension,target
0,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.30010,0.14710,0.2419,0.07871,...,17.33,184.60,2019.0,0.16220,0.66560,0.7119,0.2654,0.4601,0.11890,0
1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.08690,0.07017,0.1812,0.05667,...,23.41,158.80,1956.0,0.12380,0.18660,0.2416,0.1860,0.2750,0.08902,0
2,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.19740,0.12790,0.2069,0.05999,...,25.53,152.50,1709.0,0.14440,0.42450,0.4504,0.2430,0.3613,0.08758,0
3,11.42,20.38,77.58,386.1,0.14250,0.28390,0.24140,0.10520,0.2597,0.09744,...,26.50,98.87,567.7,0.20980,0.86630,0.6869,0.2575,0.6638,0.17300,0
4,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.19800,0.10430,0.1809,0.05883,...,16.67,152.20,1575.0,0.13740,0.20500,0.4000,0.1625,0.2364,0.07678,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564,21.56,22.39,142.00,1479.0,0.11100,0.11590,0.24390,0.13890,0.1726,0.05623,...,26.40,166.10,2027.0,0.14100,0.21130,0.4107,0.2216,0.2060,0.07115,0
565,20.13,28.25,131.20,1261.0,0.09780,0.10340,0.14400,0.09791,0.1752,0.05533,...,38.25,155.00,1731.0,0.11660,0.19220,0.3215,0.1628,0.2572,0.06637,0
566,16.60,28.08,108.30,858.1,0.08455,0.10230,0.09251,0.05302,0.1590,0.05648,...,34.12,126.70,1124.0,0.11390,0.30940,0.3403,0.1418,0.2218,0.07820,0
567,20.60,29.33,140.10,1265.0,0.11780,0.27700,0.35140,0.15200,0.2397,0.07016,...,39.42,184.60,1821.0,0.16500,0.86810,0.9387,0.2650,0.4087,0.12400,0
568,7.76,24.54,47.92,181.0,0.05263,0.04362,0.00000,0.00000,0.1587,0.05884,...,30.37,59.16,268.6,0.08996,0.06444,0.0000,0.0000,0.2871,0.07039,1

In [935]:
breast_cancer_data_df.target.value_counts()

target
1    357
0    212
Name: count, dtype: int64

## 3. Data Understanding

### Note: 
- 0 - Malignant 
- 1 - Benign

In [936]:
breast_cancer_data_df.shape

(569, 31)

In [937]:
breast_cancer_data_df.isna().sum()

mean radius                0
mean texture               0
mean perimeter             0
mean area                  0
mean smoothness            0
mean compactness           0
mean concavity             0
mean concave points        0
mean symmetry              0
mean fractal dimension     0
radius error               0
texture error              0
perimeter error            0
area error                 0
smoothness error           0
compactness error          0
concavity error            0
concave points error       0
symmetry error             0
fractal dimension error    0
worst radius               0
worst texture              0
worst perimeter            0
worst area                 0
worst smoothness           0
worst compactness          0
worst concavity            0
worst concave points       0
worst symmetry             0
worst fractal dimension    0
target                     0
dtype: int64

In [938]:
breast_cancer_data_df.dtypes

mean radius                float64
mean texture               float64
mean perimeter             float64
mean area                  float64
mean smoothness            float64
mean compactness           float64
mean concavity             float64
mean concave points        float64
mean symmetry              float64
mean fractal dimension     float64
radius error               float64
texture error              float64
perimeter error            float64
area error                 float64
smoothness error           float64
compactness error          float64
concavity error            float64
concave points error       float64
symmetry error             float64
fractal dimension error    float64
worst radius               float64
worst texture              float64
worst perimeter            float64
worst area                 float64
worst smoothness           float64
worst compactness          float64
worst concavity            float64
worst concave points       float64
worst symmetry             float64
worst fractal dimension    float64
target                       int64
dtype: object

In [939]:
breast_cancer_data_df.describe()

,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,mean fractal dimension,...,worst texture,worst perimeter,worst area,worst smoothness,worst compactness,worst concavity,worst concave points,worst symmetry,worst fractal dimension,target
count,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,...,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000
mean,14.127292,19.289649,91.969033,654.889104,0.096360,0.104341,0.088799,0.048919,0.181162,0.062798,...,25.677223,107.261213,880.583128,0.132369,0.254265,0.272188,0.114606,0.290076,0.083946,0.627417
std,3.524049,4.301036,24.298981,351.914129,0.014064,0.052813,0.079720,0.038803,0.027414,0.007060,...,6.146258,33.602542,569.356993,0.022832,0.157336,0.208624,0.065732,0.061867,0.018061,0.483918
min,6.981000,9.710000,43.790000,143.500000,0.052630,0.019380,0.000000,0.000000,0.106000,0.049960,...,12.020000,50.410000,185.200000,0.071170,0.027290,0.000000,0.000000,0.156500,0.055040,0.000000
25%,11.700000,16.170000,75.170000,420.300000,0.086370,0.064920,0.029560,0.020310,0.161900,0.057700,...,21.080000,84.110000,515.300000,0.116600,0.147200,0.114500,0.064930,0.250400,0.071460,0.000000
50%,13.370000,18.840000,86.240000,551.100000,0.095870,0.092630,0.061540,0.033500,0.179200,0.061540,...,25.410000,97.660000,686.500000,0.131300,0.211900,0.226700,0.099930,0.282200,0.080040,1.000000
75%,15.780000,21.800000,104.100000,782.700000,0.105300,0.130400,0.130700,0.074000,0.195700,0.066120,...,29.720000,125.400000,1084.000000,0.146000,0.339100,0.382900,0.161400,0.317900,0.092080,1.000000
max,28.110000,39.280000,188.500000,2501.000000,0.163400,0.345400,0.426800,0.201200,0.304000,0.097440,...,49.540000,251.200000,4254.000000,0.222600,1.058000,1.252000,0.291000,0.663800,0.207500,1.000000

## 4. Data Preperation

## 5. Model Building

In [940]:
X = breast_cancer_data_df.drop(labels=["target"], axis=1)
X.head()

,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,mean fractal dimension,...,worst radius,worst texture,worst perimeter,worst area,worst smoothness,worst compactness,worst concavity,worst concave points,worst symmetry,worst fractal dimension
0,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,0.07871,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,0.05667,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,0.05999,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,0.09744,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,0.05883,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [941]:
y = breast_cancer_data_df["target"]
y.head()

0    0
1    0
2    0
3    0
4    0
Name: target, dtype: int64

In [942]:
print(f"X_Shape: {X.shape}")
print(f"y_Shape: {y.shape}")

X_Shape: (569, 30)
y_Shape: (569,)

In [943]:
# plt.pie(x = y.value_counts(), labels=["Benign", "Malignant"], autopct="%1.0f%%")
# plt.show()

In [944]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=123, stratify=y)

In [945]:
print(f"Train Data Shape: {X_train.shape}, {y_train.shape}")
print(f"Test Data Shape: {X_test.shape}, {y_test.shape}")

Train Data Shape: (455, 30), (455,)
Test Data Shape: (114, 30), (114,)

In [946]:
print(f"Train Data Value Count:\n {round(y_train.value_counts(normalize=True)*100, 3)}")
print("-----------")
print(f"Test Data Value Count:\n {round(y_test.value_counts(normalize=True)*100, 3)}")

Train Data Value Count:
 target
1    62.637
0    37.363
Name: proportion, dtype: float64
-----------
Test Data Value Count:
 target
1    63.158
0    36.842
Name: proportion, dtype: float64

In [947]:
# plt.pie(x = y_train.value_counts(), labels=["Benign", "Malignant"], autopct="%1.0f%%")
# plt.show()

In [948]:
# plt.pie(x = y_test.value_counts(), labels=["Benign", "Malignant"], autopct="%1.0f%%")
# plt.show()

## 6. Model Training

In [949]:


dt_model = DecisionTreeClassifier(criterion="gini", max_depth=3, class_weight={0:2, 1:1})
dt_model.fit(X_train, y_train)

DecisionTreeClassifier(class_weight={0: 2, 1: 1}, max_depth=3)

## 7. Model Testing and

In [950]:
y_pred_train = dt_model.predict(X_train)

In [951]:
y_pred_test = dt_model.predict(X_test)

## 8. Model Evaluation

In [952]:
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score

#### 8.1 Train Data

In [953]:
print(classification_report(y_train, y_pred_train))

              precision    recall  f1-score   support

           0       0.92      0.97      0.94       170
           1       0.98      0.95      0.96       285

    accuracy                           0.96       455
   macro avg       0.95      0.96      0.95       455
weighted avg       0.96      0.96      0.96       455

In [954]:
print(confusion_matrix(y_train, y_pred_train))

[[165   5]
 [ 15 270]]

#### 8.2 Test Data

In [955]:
print(classification_report(y_test, y_pred_test))

              precision    recall  f1-score   support

           0       0.89      0.95      0.92        42
           1       0.97      0.93      0.95        72

    accuracy                           0.94       114
   macro avg       0.93      0.94      0.93       114
weighted avg       0.94      0.94      0.94       114

In [956]:
print(confusion_matrix(y_test, y_pred_test))

[[40  2]
 [ 5 67]]

---

In [957]:
## Before Scaling Mean and Standard Deviation
pd.DataFrame({"Mean" : X.mean(), "Std" : X.std()})

                               Mean         Std
mean radius               14.127292    3.524049
mean texture              19.289649    4.301036
mean perimeter            91.969033   24.298981
mean area                654.889104  351.914129
mean smoothness            0.096360    0.014064
mean compactness           0.104341    0.052813
mean concavity             0.088799    0.079720
mean concave points        0.048919    0.038803
mean symmetry              0.181162    0.027414
mean fractal dimension     0.062798    0.007060
radius error               0.405172    0.277313
texture error              1.216853    0.551648
perimeter error            2.866059    2.021855
area error                40.337079   45.491006
smoothness error           0.007041    0.003003
compactness error          0.025478    0.017908
concavity error            0.031894    0.030186
concave points error       0.011796    0.006170
symmetry error             0.020542    0.008266
fractal dimension error    0.003795    0.002646
worst radius              16.269190    4.833242
worst texture             25.677223    6.146258
worst perimeter          107.261213   33.602542
worst area               880.583128  569.356993
worst smoothness           0.132369    0.022832
worst compactness          0.254265    0.157336
worst concavity            0.272188    0.208624
worst concave points       0.114606    0.065732
worst symmetry             0.290076    0.061867
worst fractal dimension    0.083946    0.018061

In [958]:
from sklearn.preprocessing import StandardScaler, MinMaxScaler, RobustScaler

In [959]:
# std_scalar = StandardScaler()
# std_scalar = RobustScaler()
std_scalar = MinMaxScaler()
scaled_X = pd.DataFrame(std_scalar.fit_transform(X), columns=breast_cancer_data.feature_names)

In [960]:
## After Scaling Mean and Standard Deviation
pd.DataFrame({"Mean" : scaled_X.mean(), "Std" : scaled_X.std()})

                             Mean       Std
mean radius              0.338222  0.166787
mean texture             0.323965  0.145453
mean perimeter           0.332935  0.167915
mean area                0.216920  0.149274
mean smoothness          0.394785  0.126967
mean compactness         0.260601  0.161992
mean concavity           0.208058  0.186785
mean concave points      0.243137  0.192857
mean symmetry            0.379605  0.138456
mean fractal dimension   0.270379  0.148702
radius error             0.106345  0.100421
texture error            0.189324  0.121917
perimeter error          0.099376  0.095267
area error               0.062636  0.084967
smoothness error         0.181119  0.102067
compactness error        0.174439  0.134498
concavity error          0.080540  0.076227
concave points error     0.223454  0.116884
symmetry error           0.178143  0.116316
fractal dimension error  0.100193  0.091417
worst radius             0.296663  0.171940
worst texture            0.363998  0.163813
worst perimeter          0.283138  0.167352
worst area               0.170906  0.139932
worst smoothness         0.404138  0.150779
worst compactness        0.220212  0.152649
worst concavity          0.217403  0.166633
worst concave points     0.393836  0.225884
worst symmetry           0.263307  0.121954
worst fractal dimension  0.189596  0.118466

## Model Building

In [961]:
X_train, X_test, y_train, y_test = train_test_split(scaled_X, y, test_size=0.2, random_state=123, stratify=y)

In [962]:
print(f"Train Data Shape: {X_train.shape}, {y_train.shape}")
print(f"Test Data Shape: {X_test.shape}, {y_test.shape}")

Train Data Shape: (455, 30), (455,)
Test Data Shape: (114, 30), (114,)

In [963]:
print(f"Train Data Value Count:\n {round(y_train.value_counts(normalize=True)*100, 3)}")
print("-----------")
print(f"Test Data Value Count:\n {round(y_test.value_counts(normalize=True)*100, 3)}")

Train Data Value Count:
 target
1    62.637
0    37.363
Name: proportion, dtype: float64
-----------
Test Data Value Count:
 target
1    63.158
0    36.842
Name: proportion, dtype: float64

## 6. Model Training

In [964]:


dt_model = DecisionTreeClassifier(criterion="gini", max_depth=3, class_weight={0:2, 1:1})
dt_model.fit(X_train, y_train)

DecisionTreeClassifier(class_weight={0: 2, 1: 1}, max_depth=3)

## 7. Model Testing and

In [965]:
y_pred_train = dt_model.predict(X_train)

In [966]:
y_pred_test = dt_model.predict(X_test)

## 8. Model Evaluation

In [967]:
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score

#### 8.1 Train Data

In [968]:
print(classification_report(y_train, y_pred_train))

              precision    recall  f1-score   support

           0       0.92      0.97      0.94       170
           1       0.98      0.95      0.96       285

    accuracy                           0.96       455
   macro avg       0.95      0.96      0.95       455
weighted avg       0.96      0.96      0.96       455

In [969]:
print(confusion_matrix(y_train, y_pred_train))

[[165   5]
 [ 15 270]]

#### 8.2 Test Data

In [970]:
print(classification_report(y_test, y_pred_test))

              precision    recall  f1-score   support

           0       0.89      0.95      0.92        42
           1       0.97      0.93      0.95        72

    accuracy                           0.94       114
   macro avg       0.93      0.94      0.93       114
weighted avg       0.94      0.94      0.94       114

In [971]:
print(confusion_matrix(y_test, y_pred_test))

[[40  2]
 [ 5 67]]

In [972]:
import joblib
joblib.dump(dt_model, "model/dt_model.joblit")

['model/dt_model.joblit']

In [973]:
loaded_dt_model = joblib.load("model/dt_model.joblit")

In [974]:
prediction = loaded_dt_model.predict(X_test.iloc[[22]])
prediction

array([0])