In [26]:
import pandas as pd

In [27]:
cola_data = pd.read_excel("data/Cola.xlsx")
cola_data

,Data provided by SimFin,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Profit & Loss statement,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,in million USD,FY '09,FY '10,FY '11,FY '12,FY '13,FY '14,FY '15,FY '16,FY '17,FY '18
3,NaN,NET OPERATING REVENUES,30990,35119,46542,48017,46854,45998,44294,41863,35410,31856
4,NaN,Cost of goods sold,11088,12693,18215,19053,18421,17889,17482,16465,13255,11770
...,...,...,...,...,...,...,...,...,...,...,...,...
98,NaN,Effect of exchange rate changes on cash and ca...,576,-166,-430,-255,-611,-934,-878,-6,241,-262
99,NaN,Cash Provided by (Used in) Investing Activitie...,NaN,NaN,NaN,NaN,NaN,NaN,0,0,-58,-421
100,NaN,Cash Provided by (Used in) Financing Activitie...,NaN,NaN,NaN,NaN,NaN,NaN,0,0,-38,205
101,NaN,Net Cash Provided by (Used in) Discontinued Op...,NaN,NaN,NaN,NaN,NaN,NaN,0,0,15,91
102,NaN,Net increase (decrease) during the year,2320,1496,4286,-4361,1972,-1456,-1649,1246,-2477,2945

In [28]:
balance = cola_data.iloc[22:64, 1:]

balance = balance.T
balance.columns = [
    "Financial Year",
    "Assets",
    "Cash and cash equivalents",
    "Short-term investments",
    "Total cash, cash equivalents and short-term investments",
    "Marketable securities",
    "Trade accounts receivable, less allowances",
    "Inventories",
    "Prepaid expenses and other assets",
    "Assets held for sale",
    "Assets held for sale",
    "Total current assets",
    "Equity method investments",
    "Other investments",
    "Other assets",
    "Property, plant and equipment - net",
    "Deferred income tax assets",
    "TRADEMARKS WITH INDEFINITE LIVES",
    "BOTTLERS' FRANCHISE RIGHTS WITH INDEFINITE LIVES",
    "Goodwill",
    "Other intangible assets",
    "Total assets",
    "Liabilities",
    "Accounts payable and accrued expenses",
    "Loans and notes payable",
    "Current maturities of long-term debt",
    "Accrued income taxes",
    "Liabilities held for sale",
    "Liabilities Held for Sale, Discontinued Operations",
    "Total current liabilities",
    "Long-term debt",
    "Other liabilities",
    "Deferred income taxes",
    "Common stock",
    "Capital surplus",
    "Reinvested earnings",
    "Accumulated other comprehensive income (loss)",
    "Treasury stock, at cost",
    "EQUITY ATTRIBUTABLE TO SHAREOWNERS OF THE COCA-COLA COMPANY",
    "Equity attributable to noncontrolling interests",
    "Total equity",
    "Total liabilities and equity",
]
balance.reset_index(drop=True, inplace=True)
balance = balance.iloc[1:].reset_index(drop=True)
balance

,Financial Year,Assets,Cash and cash equivalents,Short-term investments,"Total cash, cash equivalents and short-term investments",Marketable securities,"Trade accounts receivable, less allowances",Inventories,Prepaid expenses and other assets,Assets held for sale,...,Deferred income taxes,Common stock,Capital surplus,Reinvested earnings,Accumulated other comprehensive income (loss),"Treasury stock, at cost",EQUITY ATTRIBUTABLE TO SHAREOWNERS OF THE COCA-COLA COMPANY,Equity attributable to noncontrolling interests,Total equity,Total liabilities and equity
0,FY '09,NaN,7021,2130,9151,62,3758,2354,2226,NaN,...,1580,880,8537,41537,-757,-25398,24799,547,25346,48671
1,FY '10,NaN,8517,2682,11199,138,4430,2650,3162,NaN,...,4261,880,10057,49278,-1450,-27762,31003,314,31317,72921
2,FY '11,NaN,12803,1088,13891,144,4920,3092,3450,0,...,4694,1760,10332,53621,-2774,-31304,31635,286,31921,79974
3,FY '12,NaN,8442,5017,13459,3092,4759,3264,2781,2973,...,4981,1760,11379,58045,-3385,-35009,32790,378,33168,86174
4,FY '13,NaN,10414,6707,17121,3147,4873,3277,2886,0,...,6152,1760,12276,61660,-3432,-39091,33173,267,33440,90055
5,FY '14,NaN,8958,9052,18010,3665,4466,3100,3066,679,...,5636,1760,13154,63408,-5777,-42225,30320,241,30561,92023
6,FY '15,NaN,7309,8322,15631,4269,3941,2902,2752,3900,...,4691,1760,14016,65018,-10174,-45066,25554,210,25764,89996
7,FY '16,NaN,8555,9595,18150,4051,3856,2675,2481,0,...,3753,1760,14993,65502,-11205,-47988,23062,158,23220,87270
8,FY '17,NaN,6006,9352,15358,5317,3667,2655,2000,7329,...,2522,1760,15864,60430,-10305,-50677,17072,1905,18977,87896
9,FY '18,NaN,8926,2025,10951,5013,3396,2766,1962,6546,...,1933,1760,16520,63234,-12814,-51719,16981,2077,19058,83216

In [29]:
cols = [
    "Assets",
    "Cash and cash equivalents",
    "Short-term investments",
    "Total cash, cash equivalents and short-term investments",
    "Marketable securities",
    "Trade accounts receivable, less allowances",
    "Inventories",
    "Prepaid expenses and other assets",
    "Assets held for sale",
    "Assets held for sale",
    "Total current assets",
    "Equity method investments",
    "Other investments",
    "Other assets",
    "Property, plant and equipment - net",
    "Deferred income tax assets",
    "TRADEMARKS WITH INDEFINITE LIVES",
    "BOTTLERS' FRANCHISE RIGHTS WITH INDEFINITE LIVES",
    "Goodwill",
    "Other intangible assets",
    "Total assets",
    "Liabilities",
    "Accounts payable and accrued expenses",
    "Loans and notes payable",
    "Current maturities of long-term debt",
    "Accrued income taxes",
    "Liabilities held for sale",
    "Liabilities Held for Sale, Discontinued Operations",
    "Total current liabilities",
    "Long-term debt",
    "Other liabilities",
    "Deferred income taxes",
    "Common stock",
    "Capital surplus",
    "Reinvested earnings",
    "Accumulated other comprehensive income (loss)",
    "Treasury stock, at cost",
    "EQUITY ATTRIBUTABLE TO SHAREOWNERS OF THE COCA-COLA COMPANY",
    "Equity attributable to noncontrolling interests",
    "Total equity",
    "Total liabilities and equity",
]


balance[cols] = balance[cols].apply(pd.to_numeric).astype("Int64")

ValueError: Columns must be same length as key